package io.github.kingg22.kogot.gradle.settings

/** Escapes a value for embedding in a Kotlin string literal inside the generated build script. */
private fun String.toKotlinStringLiteral(): String = "\"${replace("\\", "\\\\").replace("\"", "\\\"")}\""

private fun targetBlock(presetName: String, buildTypesLiteral: String, baseNameLiteral: String): String =
    """
    |    $presetName {
    |        binaries {
    |            sharedLib(buildTypes = $buildTypesLiteral) {
    |                baseName = $baseNameLiteral
    |            }
    |        }
    |    }
    """.trimMargin()

/**
 * Generates the `build.gradle.kts` text for [spec]'s companion export project. See
 * [KogotExportSpec]'s doc for why this is plain text generation instead of typed KGP DSL
 * configuration.
 *
 * Mirrors the hand-written pattern this replaces (compare the pre-#25
 * `mi-juego-prueba/kotlin_native_game/exported/build.gradle.kts`): same conventions plugins, same
 * `io.github.kingg22.kogot` project plugin, same `binaries.sharedLib()` DSL — just filled in from
 * [spec] instead of hand-maintained per game module.
 */
internal fun generateExportBuildScript(spec: KogotExportSpec): String {
    require(spec.targets.isNotEmpty()) {
        "kogot: export(\"${spec.modulePath}\") { } declares no targets — set KogotExportSpec.targets"
    }
    spec.buildTypes.forEach {
        require(it.lowercase() in setOf("debug", "release")) {
            "kogot: unknown build type '$it' in export spec for ${spec.modulePath}, expected debug/release"
        }
    }

    val libraryBaseName = spec.libraryBaseName ?: spec.modulePath.trimStart(':').substringAfterLast(':')
    val buildTypesLiteral = "listOf(${
        spec.buildTypes.joinToString(", ") { "NativeBuildType.${it.uppercase()}" }
    })"
    val baseNameLiteral = libraryBaseName.toKotlinStringLiteral()

    val kogotExtensionLines = buildList {
        add("    autoApplyKsp.set(false)")
        add("    autoAddDependencies.set(false)")
        add("    generateEntryPoint.set(true)")
        spec.entrySymbol?.let { add("    entrySymbol.set(${it.toKotlinStringLiteral()})") }
        spec.godotVersion?.let { add("    godotVersion.set(${it.toKotlinStringLiteral()})") }
        spec.godotProjectDir?.let { add("    godotProjectDir.set(file(${it.absolutePath.toKotlinStringLiteral()}))") }
        add("    libraryBaseName.set($baseNameLiteral)")
        spec.generatedBindingsPackage?.let { add("    generatedBindingsPackage.set(${it.toKotlinStringLiteral()})") }
        spec.generatedBindingsClassName?.let { add("    generatedBindingsClassName.set(${it.toKotlinStringLiteral()})") }
        spec.generateGdextensionFile?.let { add("    generateGdextensionFile.set($it)") }
    }

    val targetBlocks = spec.targets.joinToString("\n\n") { targetBlock(it, buildTypesLiteral, baseNameLiteral) }

    return """
        |// Generated by the kogot Gradle settings plugin for '${spec.modulePath}'. DO NOT EDIT!
        |import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
        |import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType
        |
        |plugins {
        |    alias(libs.plugins.kotlin.multiplatform.conventions)
        |    alias(libs.plugins.kotlin.styles.conventions)
        |    id("io.github.kingg22.kogot")
        |}
        |
        |kogot {
        |${kogotExtensionLines.joinToString("\n")}
        |}
        |
        |kotlin {
        |    @OptIn(ExperimentalKotlinGradlePluginApi::class)
        |    dependencies {
        |        implementation(project(${spec.modulePath.toKotlinStringLiteral()}))
        |    }
        |
        |    applyDefaultHierarchyTemplate()
        |
        |$targetBlocks
        |}
        |
    """.trimMargin()
}
