ID=io.github.kingg22.kogot
VERSION=0.1.0
GROUP=io.github.kingg22.kogot
DISPLAY_NAME=Kogot Gradle Plugin
DESCRIPTION=Gradle plugin that wires up KSP processor, GDExtension entrypoint/manifest generation, binary export and Godot CLI tasks for kogot-based Kotlin/Native Godot projects
WEBSITE=https://github.com/kingg22/kogot
VCS_URL=https://github.com/kingg22/kogot
IMPLEMENTATION_CLASS=io.github.kingg22.kogot.gradle.KogotPlugin

org.gradle.jvmargs=-Xmx4g -Xms1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
