package io.github.kingg22.kogot.processor.generators.kotlin

import io.github.kingg22.kogot.processor.model.AnnotationInfo
import io.github.kingg22.kogot.processor.model.ClassInfo
import io.github.kingg22.kogot.processor.model.TypeInfo
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Covers the `ScriptFileRegistry` generated by [GodotBindingGenerator], which maps a source file to
 * the single `@Godot` class it declares (see issue #42 — Kotlin as a Godot script language).
 */
class GodotBindingGeneratorScriptRegistryTest {
    private val generator = GodotBindingGenerator()

    private fun godotClass(qualifiedName: String, filePath: String): ClassInfo = ClassInfo(
        qualifiedName = qualifiedName,
        shortName = qualifiedName.substringAfterLast('.'),
        packageName = qualifiedName.substringBeforeLast('.'),
        supertypes = listOf(TypeInfo(qualifiedName = "io.github.kingg22.godot.api.core.Node", shortName = "Node")),
        annotations = listOf(
            AnnotationInfo(qualifiedName = "io.github.kingg22.godot.api.annotations.Godot", shortName = "Godot"),
        ),
        filePath = filePath,
    )

    private fun GenerationResult.registryContent(): String =
        files.single { it.relativePath.endsWith("ScriptFileRegistry.kt") }.content

    @Test
    fun `when a file declares exactly one Godot class, then it is addressable in the registry`() {
        val result = generator.generate(listOf(godotClass("io.github.kingg22.game.Player", "/project/src/Player.kt")))

        val content = result.registryContent()
        assertTrue(content.contains("\"/project/src/Player.kt\" to"))
        assertTrue(content.contains("KotlinScriptRegistry.Entry(\"Player\", \"Node\")"))
    }

    @Test
    fun `when a file declares two Godot classes, then neither is addressable in the registry`() {
        val classes = listOf(
            godotClass("io.github.kingg22.game.Foo", "/project/src/Multi.kt"),
            godotClass("io.github.kingg22.game.Bar", "/project/src/Multi.kt"),
        )

        val content = generator.generate(classes).registryContent()

        assertFalse(content.contains("Multi.kt"))
    }

    @Test
    fun `when multiple files each declare one Godot class, then all are addressable`() {
        val classes = listOf(
            godotClass("io.github.kingg22.game.Foo", "/project/src/Foo.kt"),
            godotClass("io.github.kingg22.game.Bar", "/project/src/Bar.kt"),
        )

        val content = generator.generate(classes).registryContent()

        assertTrue(content.contains("\"/project/src/Foo.kt\" to"))
        assertTrue(content.contains("KotlinScriptRegistry.Entry(\"Foo\", \"Node\")"))
        assertTrue(content.contains("\"/project/src/Bar.kt\" to"))
        assertTrue(content.contains("KotlinScriptRegistry.Entry(\"Bar\", \"Node\")"))
    }
}
