package io.github.kingg22.kogot.processor.generators.kotlin

import io.github.kingg22.kogot.processor.model.AnnotationInfo
import io.github.kingg22.kogot.processor.model.ClassInfo
import io.github.kingg22.kogot.processor.model.FunctionInfo
import io.github.kingg22.kogot.processor.model.GodotPrimitives
import io.github.kingg22.kogot.processor.model.ParameterInfo
import io.github.kingg22.kogot.processor.model.PropertyInfo
import io.github.kingg22.kogot.processor.model.TypeInfo
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Covers the `ScriptFileRegistry` generated by [GodotBindingGenerator], which maps a source file to
 * the single `@Godot` class it declares (see issue #42 — Kotlin as a Godot script language).
 */
class GodotBindingGeneratorScriptRegistryTest {
    private val generator = GodotBindingGenerator()

    private val exportAnnotation =
        AnnotationInfo(qualifiedName = "io.github.kingg22.godot.api.annotations.Export", shortName = "Export")
    private val exportMethodAnnotation = AnnotationInfo(
        qualifiedName = "io.github.kingg22.godot.api.annotations.ExportMethod",
        shortName = "ExportMethod",
    )

    private fun godotClass(
        qualifiedName: String,
        filePath: String,
        properties: List<PropertyInfo> = emptyList(),
        functions: List<FunctionInfo> = emptyList(),
    ): ClassInfo = ClassInfo(
        qualifiedName = qualifiedName,
        shortName = qualifiedName.substringAfterLast('.'),
        packageName = qualifiedName.substringBeforeLast('.'),
        supertypes = listOf(TypeInfo(qualifiedName = "io.github.kingg22.godot.api.core.Node", shortName = "Node")),
        annotations = listOf(
            AnnotationInfo(qualifiedName = "io.github.kingg22.godot.api.annotations.Godot", shortName = "Godot"),
        ),
        properties = properties,
        functions = functions,
        filePath = filePath,
    )

    private fun GenerationResult.registryContent(): String =
        files.single { it.relativePath.endsWith("ScriptFileRegistry.kt") }.content

    @Test
    fun `when a file declares exactly one Godot class, then it is addressable in the registry`() {
        val result = generator.generate(listOf(godotClass("io.github.kingg22.game.Player", "/project/src/Player.kt")))

        val content = result.registryContent()
        assertTrue(content.contains("\"/project/src/Player.kt\" to"))
        assertTrue(content.contains("KotlinScriptRegistry.Entry("))
        assertTrue(content.contains("\"Player\","))
        assertTrue(content.contains("\"Node\","))
        assertTrue(content.contains("properties = emptyList(),"))
        assertTrue(content.contains("methods = emptyList(),"))
    }

    @Test
    fun `when a file declares two Godot classes, then neither is addressable in the registry`() {
        val classes = listOf(
            godotClass("io.github.kingg22.game.Foo", "/project/src/Multi.kt"),
            godotClass("io.github.kingg22.game.Bar", "/project/src/Multi.kt"),
        )

        val content = generator.generate(classes).registryContent()

        assertFalse(content.contains("Multi.kt"))
    }

    @Test
    fun `when multiple files each declare one Godot class, then all are addressable`() {
        val classes = listOf(
            godotClass("io.github.kingg22.game.Foo", "/project/src/Foo.kt"),
            godotClass("io.github.kingg22.game.Bar", "/project/src/Bar.kt"),
        )

        val content = generator.generate(classes).registryContent()

        assertTrue(content.contains("\"/project/src/Foo.kt\" to"))
        assertTrue(content.contains("\"Foo\","))
        assertTrue(content.contains("\"/project/src/Bar.kt\" to"))
        assertTrue(content.contains("\"Bar\","))
    }

    @Test
    fun `when a class has exported members, then the entry references its binding trampolines`() {
        val intType = TypeInfo(qualifiedName = GodotPrimitives.INT, shortName = "Int")
        val classInfo = godotClass(
            "io.github.kingg22.game.Player",
            "/project/src/Player.kt",
            properties = listOf(
                PropertyInfo(
                    name = "health",
                    type = intType,
                    isMutable = true,
                    annotations = listOf(exportAnnotation),
                ),
                PropertyInfo(
                    name = "readOnlyStat",
                    type = intType,
                    isMutable = false,
                    annotations = listOf(exportAnnotation),
                ),
            ),
            functions = listOf(
                FunctionInfo(
                    name = "heal",
                    returnType = null,
                    parameters = listOf(ParameterInfo(name = "amount", type = intType)),
                    annotations = listOf(exportMethodAnnotation),
                ),
            ),
        )

        val content = generator.generate(listOf(classInfo)).registryContent()

        assertTrue(
            content.contains(
                "ScriptPropertyDescriptor(\"health\", Variant.Type.INT, " +
                    "Player_Binding._godot_get_health, Player_Binding._godot_set_health)",
            ),
        )
        assertTrue(
            content.contains(
                "ScriptPropertyDescriptor(\"readOnlyStat\", Variant.Type.INT, " +
                    "Player_Binding._godot_get_readOnlyStat, null)",
            ),
        )
        assertTrue(content.contains("ScriptMethodDescriptor(\"heal\", 1, Player_Binding._godot_call_heal)"))
    }
}
